#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

cmd-scheduler-nomad-report() {
  declare desc="displays a scheduler-nomad report for one or more apps"
  local cmd="scheduler-nomad:report"
  local INSTALLED_APPS=$(dokku_apps)
  local APP="$2" INFO_FLAG="$3"

  if [[ -n "$APP" ]] && [[ "$APP" == --* ]]; then
    INFO_FLAG="$APP"
    APP=""
  fi

  if [[ -z "$APP" ]] && [[ -z "$INFO_FLAG" ]]; then
    INFO_FLAG="true"
  fi

  if [[ -z "$APP" ]]; then
    for app in $INSTALLED_APPS; do
      cmd-scheduler-nomad-report-single "$app" "$INFO_FLAG" | tee || true
    done
  else
    cmd-scheduler-nomad-report-single "$APP" "$INFO_FLAG"
  fi
}

cmd-scheduler-nomad-report-single() {
  declare APP="$1" INFO_FLAG="$2"
  if [[ "$INFO_FLAG" == "true" ]]; then
    INFO_FLAG=""
  fi
  verify_app_name "$APP"
  local flag_map=(
    "--scheduler-nomad-addr: $(fn-plugin-property-get "scheduler-nomad" "$APP" "nomad-addr" "")"
    "--scheduler-nomad-datacenter: $(fn-plugin-property-get "scheduler-nomad" "$APP" "nomad-datacenter" "dc1")"
    "--scheduler-levant-version: $(levant version | head -n1)"
  )

  if [[ -z "$INFO_FLAG" ]]; then
    dokku_log_info2_quiet "${APP} scheduler-nomad information"
    for flag in "${flag_map[@]}"; do
      key="$(echo "${flag#--}" | cut -f1 -d' ' | tr - ' ')"
      dokku_log_verbose "$(printf "%-30s %-25s" "${key^}" "${flag#*: }")"
    done
  else
    local match=false; local value_exists=false
    for flag in "${flag_map[@]}"; do
      valid_flags="${valid_flags} $(echo "$flag" | cut -d':' -f1)"
      if [[ "$flag" == "${INFO_FLAG}:"* ]]; then
        value=${flag#*: }
        size="${#value}"
        if [[ "$size" -ne 0 ]]; then
          echo "$value" && match=true && value_exists=true
        else
          match=true
        fi
      fi
    done
    [[ "$match" == "true" ]] || dokku_log_fail "Invalid flag passed, valid flags:${valid_flags}"
    [[ "$value_exists" == "true" ]] || dokku_log_fail "not deployed"
  fi
}

scheduler_docker_local_help_content_func() {
  declare desc="return scheduler-nomad plugin help content"
  cat<<help_content
    scheduler-nomad:report [<app>] [<flag>], Displays a scheduler-nomad report for one or more apps
    scheduler-nomad:set <app> <property> (<value>), Set or clear a scheduler-nomad property for an app
help_content
}

cmd-scheduler-nomad-help() {
  if [[ $1 = "scheduler-nomad:help" ]] ; then
    echo -e 'Usage: dokku scheduler-nomad[:COMMAND]'
    echo ''
    echo 'Manages the scheduler-nomad integration for an app.'
    echo ''
    echo 'Additional commands:'
    scheduler_docker_local_help_content_func | sort | column -c2 -t -s,
    echo ''
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    scheduler_docker_local_help_content_func
  else
    cat<<help_desc
    scheduler-nomad, Manages the scheduler-nomad integration for an app
help_desc
  fi
}
