#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

scheduler-nomad-post-delete() {
  declare desc="scheduler-nomad post-delete plugin trigger"
  declare trigger="scheduler-nomad post-delete"
  declare APP="$1"

  local DOKKU_SCHEDULER=$(config_get "$APP" DOKKU_SCHEDULER || echo "docker-local")
  if [[ "$DOKKU_SCHEDULER" != "nomad" ]]; then
    return
  fi

  # todo: tell nomad to stop all jobs for this app
}

scheduler-nomad-post-delete "$@"
