#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-nomad-scheduler-run() {
  declare desc="scheduler-nomad scheduler-run plugin trigger"
  declare trigger="scheduler-nomad scheduler-run"
  declare DOKKU_SCHEDULER="$1" APP="$2"
  shift 2

  if [[ "$DOKKU_SCHEDULER" != "docker-local" ]]; then
    return
  fi

  dokku_log_warn "Not implemented for nomad"
}

scheduler-nomad-scheduler-run "$@"
