#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-nomad-scheduler-stop() {
  declare desc="scheduler-nomad scheduler-stop plugin trigger"
  declare trigger="scheduler-nomad scheduler-stop"
  declare DOKKU_SCHEDULER="$1" APP="$2" REMOVE_CONTAINERS="$3"
  shift 2

  if [[ "$DOKKU_SCHEDULER" != "docker-local" ]]; then
    return
  fi

  dokku_log_warn "Not implemented for nomad"
}

scheduler-nomad-scheduler-stop "$@"
