#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

scheduler-nomad-scheduler-stop() {
  declare desc="scheduler-nomad scheduler-stop plugin trigger"
  declare trigger="scheduler-nomad scheduler-stop"
  declare DOKKU_SCHEDULER="$1" APP="$2" REMOVE_CONTAINERS="$3"
  shift 2

  if [[ "$DOKKU_SCHEDULER" != "docker-local" ]]; then
    return
  fi

  local DOKKU_SCALE_FILE="$DOKKU_ROOT/$APP/DOKKU_SCALE"
  if [[ ! -f "$DOKKU_SCALE_FILE" ]]; then
    return
  fi

  _NOMAD_ADDR=$(fn-plugin-property-get "scheduler-nomad" "$APP" "nomad-addr" "")
  [[ -n "$_NOMAD_ADDR" ]] && export NOMAD_ADDR="$_NOMAD_ADDR"

  while read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^#.* ]] && continue
    line="$(strip_inline_comments "$line")"
    PROC_TYPE=${line%%=*}

    levant scale-in -percent 100 -task-group "${APP}-${PROC_TYPE}" "${APP}-${PROC_TYPE}"
  done < "$DOKKU_SCALE_FILE"
}

scheduler-nomad-scheduler-stop "$@"
